# Logistic Regression Implementation

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import make_classification

## 2. Creation of the dataset

In [3]:
x, y = make_classification(
    n_samples=1000,
    n_features=10,
    n_classes=2,
    random_state=42
)

In [4]:
x[:4]

array([[ 0.96479937, -0.06644898,  0.98676805, -0.35807945,  0.99726557,
         1.18189004, -1.61567885, -1.2101605 , -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409,  0.83161679, -1.17696211,
         1.82054391,  1.75237485, -0.98453405,  0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 ,  0.79381847, -0.26864575,
        -1.83635978,  1.23908594, -0.2463834 , -1.05814521, -0.29737608],
       [ 1.75041163,  2.02360622,  1.68815935,  0.00679984, -1.60766103,
         0.18474058, -2.61942676, -0.35744542, -1.47312719, -0.19003904]])

In [5]:
y[:4]

array([0, 1, 1, 0])

In [6]:
pd.DataFrame(x)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

## 3. Preprocessing the dataset

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.3,
    random_state=42
)

In [8]:
x_train.shape, x_test.shape

((700, 10), (300, 10))

In [9]:
y_train.shape, y_test.shape

((700,), (300,))

## 4. Model training

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
log_model = LogisticRegression()
log_model.fit(x_train, y_train)

LogisticRegression()

In [12]:
y_pred = log_model.predict(x_test)
print(y_pred)

[0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 1
 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1
 0 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1 1 0 1 1
 1 1 1 0]


In [13]:
from pprint import pprint
y_pred_prob = log_model.predict_proba(x_test)

for i in y_pred_prob:
    print(f"{np.argmax(i)} => {i[np.argmax(i)]*100:.2f}%")

0 => 77.45%
1 => 96.63%
0 => 67.07%
1 => 92.01%
0 => 97.66%
1 => 95.86%
0 => 97.90%
0 => 95.94%
0 => 80.85%
0 => 68.50%
0 => 91.37%
1 => 73.64%
0 => 52.58%
1 => 78.81%
0 => 79.36%
0 => 94.66%
1 => 97.37%
1 => 67.58%
1 => 68.52%
1 => 79.50%
0 => 50.46%
0 => 96.67%
1 => 79.95%
0 => 77.79%
0 => 87.30%
1 => 95.98%
0 => 92.12%
0 => 81.43%
1 => 51.57%
1 => 65.40%
1 => 93.17%
1 => 99.95%
0 => 96.93%
0 => 97.29%
0 => 94.24%
0 => 51.93%
1 => 91.54%
1 => 67.40%
1 => 52.31%
1 => 99.98%
0 => 91.59%
1 => 91.35%
1 => 52.05%
0 => 93.57%
0 => 97.79%
0 => 58.56%
1 => 98.42%
1 => 92.38%
1 => 98.65%
1 => 94.70%
0 => 80.64%
1 => 99.52%
0 => 50.48%
0 => 86.84%
1 => 99.11%
0 => 59.25%
1 => 84.26%
0 => 97.64%
1 => 90.14%
0 => 90.42%
1 => 99.33%
0 => 69.48%
0 => 75.76%
1 => 96.90%
1 => 69.33%
1 => 82.52%
0 => 83.65%
0 => 89.75%
1 => 66.38%
1 => 83.64%
1 => 67.72%
1 => 95.52%
1 => 99.98%
0 => 96.86%
1 => 81.47%
0 => 87.61%
0 => 97.46%
1 => 99.83%
0 => 94.25%
1 => 83.30%
0 => 79.37%
0 => 94.08%
1 => 89.84%
0 =>

## 5. Performance Metrics

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [15]:
score = accuracy_score(y_test, y_pred)
print(score)

0.8466666666666667


In [16]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[118  17]
 [ 29 136]]


In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

